train_set_file: "data/xsum/bart-base/train_distribution.parquet"
val_set_file: "data/xsum/bart-base/validation_encoder_decoder.parquet"
test_set_file: "data/xsum/bart-base/test_encoder_decoder.parquet"
num_workers: 4
batch_size: 8
model_name: facebook/bart-base
